diem/move

language/tools/move-cli/tests/testsuite/explain_user_module_abort/args.exp
language/tools/move-cli/tests/testsuite/explain_user_module_abort/args.txt
language/tools/move-cli/tests/testsuite/explain_user_module_abort/scripts/fail_script.move

Mac is case sensitive, cannot have scripts and sources with the same name.

Fix failing test due to name conflict

---

Cargo.lock
language/tools/move-cli/tests/cli_tests.rs
language/tools/move-cli/tests/cross_process_tests/Package1/Move.toml
language/tools/move-cli/tests/cross_process_tests/Package1/sources/Dummy.move
language/tools/move-cli/tests/cross_process_tests/Package2/Move.toml
language/tools/move-cli/tests/cross_process_tests/Package2/sources/Dummy.move
language/tools/move-package/Cargo.toml
language/tools/move-package/src/lib.rs
language/tools/move-package/src/package_lock.rs
language/tools/move-package/tests/test_thread_safety.rs
language/tools/move-package/tests/thread_safety_package_test_sources/Package1/Move.toml
language/tools/move-package/tests/thread_safety_package_test_sources/Package1/sources/Dummy.move
language/tools/move-package/tests/thread_safety_package_test_sources/Package2/Move.toml
language/tools/move-package/tests/thread_safety_package_test_sources/Package2/sources/Dummy.move

This PR adds a global package lock to the Move package manager: we have both a thread-local mutex and cross-process locking. The issue that this PR resolves was especially apparent when dealing with git dependencies. This PR also adds two tests to make sure that these locks are being respected by threads and processes and solve the issues reported in https://github.com/diem/diem/issues/10102.

[move-package] Make package system thread/process safe

---

language/tools/move-cli/README.md

Current paths were incorrect after the repository was moved from /diem/diem to /diem/move. Adjust paths to reflect the correct locations. Additional items were found since the last pull request
Yes
N/A
N/A
N/A

Update move cli documentation

---

language/move-prover/boogie-backend/src/boogie_wrapper.rs
language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/bytecode/src/spec_instrumentation.rs
language/move-prover/bytecode/src/stackless_bytecode.rs
language/move-prover/interpreter/src/concrete/player.rs
language/move-prover/tests/sources/functional/trace.cvc5_exp
language/move-prover/tests/sources/functional/trace.exp
language/move-prover/tests/sources/functional/trace.move

A new feature to print out the content of the related global memory along with the counter example trace when "--trace" is set in the prover. In this PR, we define the global memory as the memory that is accessed in the function where the verification fails.
The output looks like:
```
=         Resource name: DiemTimestamp_CurrentTimeMicroseconds 
=         Values: 
=           {
=             Address(173345816): DiemTimestamp.CurrentTimeMicroseconds{
=               microseconds = 18446744073709551615},
=             Default: DiemTimestamp.CurrentTimeMicroseconds{
=               microseconds = 18446744073709551615}}
```
Yes
cargo test

[move-prover] Print out global memory in the counterexample trace

---

language/documentation/tutorial/README.md

Recently the Move repository location was changed. This affected paths within different documentation. In this case, the user could not download the move-analyser and other links did not point to the correct directories.
Yes
N/A
N/A
* Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
* Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
* Why we must have it for V1 launch.
* What workarounds and alternative we have if we do not push the PR.

Update tutorial docuentation

---

language/move-compiler/src/cfgir/absint.rs
language/move-compiler/src/cfgir/cfg.rs
language/move-compiler/src/cfgir/liveness/mod.rs
language/move-compiler/tests/move_check/borrows/borrow_field_combo_invalid.exp
language/move-compiler/tests/move_check/locals/use_after_move_if_else.exp

- Use reverse post-order traversal for source language CFG
- Will allow for warnings in the future on type-system checks that require fix-point iteration
- We want to change the rules of the bytecode verifier to not require fix-point iteration for its rules
- This refactor will allow for these sorts of constraints to exist for the source language too
- internal only change
- ran the tests

[move-compiler] Improve CFG traversal

---

language/move-prover/bytecode/src/stackless_bytecode.rs

Fixing AST printing for shift right operation to print ">>" instead of "<<".
Yes

Fix typo in AST printing for shift right

---

Cargo.lock
language/move-binary-format/src/access.rs
language/tools/move-bytecode-utils/Cargo.toml
language/tools/move-bytecode-utils/src/layout.rs
language/tools/move-cli/src/sandbox/cli.rs
language/tools/move-cli/src/sandbox/commands/generate.rs
language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
language/tools/move-cli/tests/testsuite/generate_struct_layout/args.exp
language/tools/move-cli/tests/testsuite/generate_struct_layout/args.txt
language/tools/move-cli/tests/testsuite/generate_struct_layout/sources/M1.move

This PR resurrects an earlier [PR](https://github.com/diem/diem/pull/9424) by @sblackshear and at this point it mainly adapts the older implementation to the updated Move codebase with the same functionality. 
It's the same as before, that is for this change to be combined with serde-generate to codegen type definitions for Move structs in a variety of languages.
- Add logic for generating serde-friendly layout YAML for Move struct definitions. Only works for closed types (i.e., no unbound type parameters).
- The generation works in two modes: deep (recursively generate layout YAML for given struct and all its deps) or shallow (given struct only, leave deps as typenames).
- Exposed generation in both modes via CLI + added tests.
Yes
Additional tests verifying the new layout format have …

[move-tools] Serde-friendly type layout generation from modules

---

language/evm/examples/sources/ERC1155.move
language/evm/examples/sources/ERC20.move
language/evm/examples/sources/Table.move
language/evm/examples/sources/Token.move

This PR adds the Table module and ERC20 and ERC1155 implementations using Table.
Most of the functions in the Table module are declared to be native. They may be compiled into the Solidity-like maps by the Move-to-EVM compiler. Moreover, although it is slow, it's possible to run them on MoveVM today because they can be easily implemented using vector in Move. It can become faster in the future once Move supports an efficient map type.
As for the ERC20 contract, the differences from the original implementation (Token.move) are as follows:
- Table is used
- All data structures go to the single struct called `State` (which correspond to the contract state in Solidity)
- State is published when the contract is deployed and the constructor is called.
- signers are not required for adding …

ERC20 and ERC1155 implementations with Table

---

language/tools/move-cli/src/sandbox/commands/run.rs

fix the logical bug when executing command 'move sandbox run'
Sometimes when executing command 'move sandbox run' in a package, it will prompt the error message such as "Unable to find script in file xxxx"
When digging more deeper of the codes, It seems like the logic in the current implementation of the command  'move sandbox run'  is not correct all the time, it just compares the filename between the compiled packages and the user inputted script name, but move-compiler has done some renaming when compiling the source codes. It would be better to compare the FileHash other than the file name to determine the correct compiled script to execute 
(Write your answer here.)
(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your …

bug fix when executing command 'move sandbox run'

---

language/move-vm/runtime/src/data_cache.rs
language/move-vm/runtime/src/native_functions.rs
language/move-vm/types/src/data_store.rs

This will allow us to read past events when processing native functions calls.
Doing so will allow us to be able to test custom Move events in our repo.
There are also many other useful ways of using this for testing.

Expose read to event store from NativeContext

---

Cargo.lock
Cargo.toml
crates/workspace-hack/Cargo.toml
language/evm/exec-utils/Cargo.toml
language/evm/exec-utils/contracts/a_plus_b.sol
language/evm/exec-utils/contracts/hello_world.sol
language/evm/exec-utils/contracts/two_functions.sol
language/evm/exec-utils/src/compile.rs
language/evm/exec-utils/src/exec.rs
language/evm/exec-utils/src/lib.rs
language/evm/exec-utils/src/tests.rs
x.toml

This introduces a crate `evm-exec-utils`, which contains some wrappers around compiling solidity code (for testing) and executing EVM bytecode using [SputnikVM](https://github.com/rust-blockchain/evm). 
Right now, this has limited functionalities and some of the parameters might not having been properly set up. We'll explore and fix them over time.

[evm] initial implementation of evm execution utils

---

language/evm/exec-utils/contracts/stateful.sol
language/evm/exec-utils/src/exec.rs
language/evm/exec-utils/src/tests.rs

This makes some minor improvements to evm-test-utils:
- This fixes the bug that changes to the storage made by a call are
not applied to the backend.
- This gets rid of the hack to obtain addresses of created accounts
and replace it with a proper call to StackExecutor::create_address.

[evm][exec-utils] fix bug & better way to get addresses of created contracts

---

language/evm/exec-utils/src/exec.rs
language/evm/exec-utils/src/tests.rs

This implements some of the essential functionalities `evm-exec-utils` currently misses:
- minting
- transfer eth
- ability to execute custom code without creating a contract

[evm][exec-utils] implement mint, transfer_eth, execute_custom_code

---

.github/actions/build-setup/action.yml
docker/ci/github/Dockerfile
scripts/dev_setup.sh

Per https://github.com/diem/move/issues/25, The dev_setup script installs many things (terraform, kubernetes, awscli, ...) that aren't needed to run Move. 
Aside from above-mentioned, I also looked into the following modules in dev_setup.sh and removed the Codegen tool and API build tool that are only used in `diem/diem`
<table>
<tr>
<td> Decision
<td> Module
<td> Callsites in Diem/move
<td> Callsites in Diem/Diem
<tr>
<td> Solidity
<td> Keep
<td> https://github.com/diem/move/search?q=solidity
<td> N/A
<tr>
<td> Remove
<td> CodeGen Tool
<td> [N/A](https://github.com/diem/move/search?q=swift)
<td> https://github.com/diem/diem/blob/dbbc96c7c3ae936bdf60744fd9055a5835b060d2/diem-move/transaction-builder-generator/README.md
<tr>
<td> Remove
<td> API Build Tool
<td> …

Simplify dev_setup script

---

language/evm/move-to-yul/src/functions.rs
language/evm/move-to-yul/src/generator.rs
language/evm/move-to-yul/src/yul_functions.rs
language/evm/move-to-yul/tests/Arithm.exp
language/evm/move-to-yul/tests/ControlStructures.exp
language/evm/move-to-yul/tests/Locals.exp
language/evm/move-to-yul/tests/Locals.move
language/evm/move-to-yul/tests/MoveCalls.exp
language/evm/move-to-yul/tests/NoGenericCallable.exp
language/evm/move-to-yul/tests/Resources.exp
language/evm/move-to-yul/tests/Structs.exp
language/evm/move-to-yul/tests/Structs.move
language/evm/move-to-yul/tests/U256Arith.exp
language/evm/move-to-yul/tests/fallback-receive-test/FallbackOnly.exp
language/evm/move-to-yul/tests/fallback-receive-test/FallbackPayableOnly.exp
language/evm/move-to-yul/tests/fallback-receive-test/ReceiveFallback.exp
language/evm/move-to-yul/tests/fallback-receive-test/ReceiveOnly.exp
language/evm/move-to-yul/tests/fallback-receive-test/expect-failure/FallbackMultipleParams.exp
language/evm/move-to-yul/tests/fallback-receive-test/expect-failure/FallbackReciveFailure.exp
language/evm/move-to-yul/tests/test-dispatcher/DispatcherBasic.exp
language/evm/move-to-yul/tests/test-dispatcher/DispatcherFallback.exp
language/evm/move-to-yul/tests/test-dispatcher/DispatcherRevert.exp

This turns the code examples in `tests/Structs.move` and `tests/Locals.move` into tests, and fixes bugs on the way in the handling of references and structs. At this point, we have basic things like packing and unpacking structs, and working with references to locals and to fields working.
There where two major bugs in the memory primitives: (a) calling `shl` and `shr` with wrong parameter order (b) wrongly assuming low endian architecture for packing bytes in words. Unfortunately, the big endian architecture makes things a bit more tricky. So most of the primitives around LoadUNN and StoreUNN are rewritten. Notice this does not yet test storage, only memory.
EVM
Yes
New tests

[move-to-yul] Fixes to memory primitives & passing basic reference and struct tests

---

language/move-stdlib/tests/BCSTests.move
language/move-stdlib/tests/EventTests.move
language/move-vm/runtime/Cargo.toml
language/move-vm/runtime/src/lib.rs
language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/tracing.rs
language/tools/move-cli/Cargo.toml
language/tools/move-cli/tests/cli_tests.rs
language/tools/move-cli/tests/cli_testsuite.rs

PR #95 is experiencing stack overflows in some unrelated tests. After some analysis, it appears that is caused by some stress tests in `BCSTests` and `EventTests` which construct (via generics) types which have a nesting depth of 256 and are excercising the VALUE_DEPTH_MAX constant in the VM. In debug builds this constants value is simply to high, as it triggers the recursive computation of a TypeLayout.
This PR reduces the size of VALUE_DEPTH_MAX to 128 and adopts the existing tests accordingly. A max depth of 128 seems more than sufficient. (It means, in practice, that a user cannot nest more than 128 struct types.)
The PR also enables release builds of the Move CLI and therefore unit tests. This will allow in the future to analyze such failures, as it is well known that Rust in debug …

[move-vm] Reduce VALUE_DEPTH_MAX to 128 + enable release build for CLI

---

language/move-binary-format/src/errors.rs
language/move-prover/interpreter-testsuite/tests/concrete_check_testsuite.rs
language/move-prover/interpreter/src/shared/bridge.rs
language/move-stdlib/src/natives/vector.rs
language/move-vm/runtime/Cargo.toml
language/move-vm/runtime/src/interpreter.rs
language/move-vm/runtime/src/logging.rs
language/move-vm/types/src/natives/function.rs
language/tools/move-unit-test/Cargo.toml
language/tools/move-unit-test/src/lib.rs
language/tools/move-unit-test/src/test_reporter.rs
language/tools/move-unit-test/src/test_runner.rs
language/tools/move-unit-test/tests/move_unit_test_testsuite.rs
language/tools/move-unit-test/tests/test_sources/missing_data.exp

It can be very useful to see the stacktrace when a test aborted.
Added a stacktrace field to the vm error types, and propagate it if the testing feature is enabled.
Add an option to the test config to turn it on. If the option is not enabled, we remove the stacktrace so it's not printed.

Add option to print stacktrace upon abort during Move tests

---

language/evm/move-to-yul/src/attributes.rs
language/evm/move-to-yul/src/generator.rs
language/evm/move-to-yul/src/native_functions.rs
language/tools/move-unit-test/src/test_reporter.rs
language/tools/move-unit-test/src/test_runner.rs
language/tools/move-unit-test/tests/test_sources/address_args.evm.exp
language/tools/move-unit-test/tests/test_sources/address_args.exp
language/tools/move-unit-test/tests/test_sources/address_args.move
language/tools/move-unit-test/tests/test_sources/non_exsistent_native.evm.exp
language/tools/move-unit-test/tests/test_sources/non_exsistent_native.exp
language/tools/move-unit-test/tests/test_sources/non_exsistent_native.move
language/tools/move-unit-test/tests/test_sources/proposal_test.evm.exp
language/tools/move-unit-test/tests/test_sources/signer_args.evm.exp

This allows arguments (`#[test(a = ...)]`) to be used in EVM-based unit tests. 
It should be noted that right now, the unit test framework itself only supports address arguments (passed to parameters of `signer` or `address` types), so this is all we get for EVM-based unit tests.

[evm] support arguments in evm-based unit tests

---

language/evm/examples/sources/IERC20.move
language/evm/examples/sources/IUniswapV2Factory.move
language/evm/examples/sources/IUniswapV2Router.move
language/evm/examples/sources/TestUniswap.move
language/evm/examples/sources/TestUniswapLiquidity.move
language/evm/stdlib/sources/U256.move

This PR adds a user (client) contract of UniswapV2. The Move modules
interact with the existing UniswapV2 contract via the external functions
which are defined in the "interface" modules (e.g., `IERC20.move`). The
external functions define their signatures as attributes. For example,
`#[external(sig=b"transferFrom(address,address,uint) returns (bool)")]`
This PR also adds a couple of new native functions such as
`Evm::block_timestamp` and `U256::to_address`.
TODO: In this PR, Ethereum addresses (20 bytes long) are defined as
local variables (using `u256_from_words`) rather than module constants.
This can be fixed once Move supports 20 byte long addresses and
literals.
To add an example which interacts with some existing contract via external calls
yes
cargo test

Added a Move example to interact with the existing UniswapV2

---

language/testing-infra/transactional-test-runner/src/tasks.rs
language/testing-infra/transactional-test-runner/src/vm_test_harness.rs

This is to solve the bugs identified in https://github.com/diem/move/issues/118. The current test has the assumption that the AccountAddress is 16-bytes and hard code this assumption in the code. 
Yes
cargo test -p move-transactional-test-runner passed
cargo x lint && cargo xfmt && cargo xclippy --all-targets
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)
* Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
* Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
* Why we must have it for V1 launch.
* What workarounds and alternative we have if we do not push the …

[bug] fix tests broken for non-16 byte address

---

language/move-compiler/src/attr_derivation/evm_deriver.rs
language/move-compiler/src/attr_derivation/mod.rs
language/move-compiler/src/command_line/mod.rs
language/move-compiler/src/lib.rs
language/move-compiler/src/parser/syntax.rs
language/move-compiler/src/shared/mod.rs
language/move-compiler/tests/move_check/flavors/evm/derive.exp
language/move-compiler/tests/move_check/flavors/evm/derive.move
language/move-compiler/tests/move_check_testsuite.rs

This adds a basic framework for deriving code from attributes:
- adds a new flag `--flavor=<name>` to the Move compiler. The first instance in this PR of this is `--flavor=evm`.
- adds a new module `attr_derivation` to the compiler. This dispatches depending on flavor to domain specific attribute derivers. The first instance of this is the `evm_deriver`. Next use will be for Async Move.
- the derivers are called after parsing and before expansion (this is necessary because expansion does some form of name resolution and we need to add derived functions before its running)
- in `evm_deriver`, we recognize the attribute `#[callable]` and derive a `call_XXX(contract: address, ...)` native function from this, which will be automatically implemented by the EVM backend.
Extensibility
Yes

[move-compiler] Attribute code derivation

---

language/move-vm/runtime/src/runtime.rs
language/move-vm/runtime/src/session.rs

Currently function to enter VM execution take fully owned vectors of `[u8]` only to promptly deserialize them and drop the vectors. This requires VM users to continuously clone, and live with endless allocations / deallocations. 
The solution is to make the `args` input to `execute_function_for_effects` into an `args: Vec<V>`, with `V` being a generic type with `V: Borrow<[u8]>`. And fix called functions to do the same. This is purely a change of type and an addition of `.borrow()` to get a reference when needed, no other functionality changes. 
As a result, those who enjoy passing `Vec<u8>`s around can continue to do so, while others can pass in types that provide a &[u8] without allocations.
Yes.
All tests pass.

Change type of `args` inputs to `execute_function_for_effects` to make it more flexible

---

language/documentation/book/src/coding-conventions.md

Move seems to support block doc comments /** */.
It seems that the document does not make style recommendations on the
comment style, therefore listing all the possible comment options here.
**This PR was originally opened against `diem` repository: https://github.com/diem/diem/pull/9660**
(The Stale bot reminded me that the PR was still open)
(Write your motivation for proposed changes here.)
Yes (the whole file, the anchor "pull-requests" doesn't exist anymore).
Documentation-only change (book).
Original PR (now closed): https://github.com/diem/diem/pull/9660

[move-book] Added block doc comment option

---

language/evm/examples/sources/ERC1155.move
language/evm/examples/sources/ERC20.move
language/evm/examples/sources/Token.move
language/evm/examples/tests/ERC1155Tests.move
language/evm/examples/tests/ERC20Tests.move
language/evm/move-to-yul/src/native_functions.rs
language/evm/stdlib/sources/Evm.move
language/move-stdlib/docs/ASCII.md
language/move-stdlib/sources/ASCII.move

This PR adds some unit tests for ERC20 and ERC1155 contracts, so it
tests out both Emma's Table implementation and Victor's unit testing
support in CLI.
It turns out that the unit testing in move-cli has some issue. See a minimal
example to reproduce the issue in `evm/examples/tests/ERC20Tests.move`.
Instead, this PR adds the unit tests to the `cargo test` testsuite of
the the `move-to-yul` crate.
In addition, this PR:
- implements the "ownable" pattern for ERC1155, and made ERC1155
mintable
- allows the initial supply for ERC20
- implements the translation of the native function `Evm::self()`
TODO:
- event-related code is commented out because it's not supported in unit testing at the moment.
- `Std::ASCII::is_valid_char` used to use the parameter name `byte` which is incompatible with …

[evm] Added unit tests for ERC20 and ERC1155 contracts

---

Cargo.lock
language/move-binary-format/src/errors.rs
language/move-core/types/src/vm_status.rs
language/move-stdlib/src/natives/mod.rs
language/move-vm/runtime/src/interpreter.rs
language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/native_functions.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/runtime/src/session.rs
language/move-vm/types/src/gas_schedule.rs
language/move-vm/types/src/values/values_impl.rs

[This PR has been split from #142 for better transparency of this new mechanism. There are a few more functions added to the VM which are useful helpers for #142 but have no obvious need in this PR; I left them here to not complicate the split too much.]
This adds an extension mechanism to the Move VM which allows native functions to access some state defined by the execution environment. The mechanism is based on the Rust `Any` type. New variantes of the execute functions in the session (`execute_XXX_with_env_ext`) which allow to pass in the extension which can then be consumed by natives.
No tests are in this PR as the VM doesn't have its own test suite but is tested indirectly via other crates; #142 contains a number of tests for this.
Extensible VM
Yes

[move-vm] Extension mechanism for VM state

---

language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/boogie-backend/src/prelude/prelude.bpl
language/move-prover/tests/sources/functional/arithm.move
language/move-prover/tests/sources/functional/fixed_point_arithm.exp
language/move-prover/tests/sources/functional/fixed_point_arithm.move
language/move-prover/tests/sources/functional/fixed_point_arithm.simplify_exp
language/move-prover/tests/sources/functional/shift.exp
language/move-prover/tests/sources/functional/shift.move
language/move-prover/tests/sources/functional/trace.exp
language/move-stdlib/docs/Errors.md
language/move-stdlib/sources/Errors.move

Issue #147 reported a bug in the left shift operation where the prover
failed to report an obviously violated postcondition.  The report also
observed that the shift operators were only for a few shift amounts.
It is unfortunate that the unimplemented shift amounts did not result
in a false error report.  Upon inspection of the code, I also found a
"TODO" that shift left doesn't delete bits that are shifted left of
the end of the destination.  In the prover, this would result in cases
where the unbounded integer value would exceed the upper bound imposed
by the bit width of the destination.
The use of a recursive function raises a risk of non-termination, but
it seems to work fine in test cases, including a variable shift
(somewhat to my surprise).
I made the following changes and …

[move-prover] Fixed bugs in shift

---

language/tools/move-cli/tests/move_unit_tests/assign_dev_addr_for_dep/Move.toml
language/tools/move-package/src/resolution/resolution_graph.rs
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_address_with_dep/Move.exp
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_address_with_dep/Move.toml
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_address_with_dep/deps_only/A/Move.toml
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_address_with_dev_dep/Move.exp
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_address_with_dev_dep/Move.toml
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_address_with_dev_dep/deps_only/A/Move.toml
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_addresses/Move.exp
language/tools/move-package/tests/test_sources/resolution/conflicting_dev_addresses/Move.toml
language/tools/move-package/tests/test_sources/resolution/sources/B.move

- With the recent change (#145) to named addresses being transparent, it is now possible for code to not work for every possible instantiation of addresses
- This fixes that by ensuring unassigned addresses, set in dev addresses, are assigned to a unique address
- We still need to ban/warn against non-named address qualification of module members to fully ensure packages compile properly with any mapping of named addresses 
new tests 
- Followup to #145

[move-package] Ensure dev-addresses are unique

---

language/evm/hardhat-examples/contracts/Event.abi.json
language/evm/hardhat-examples/contracts/Event.move
language/evm/hardhat-examples/contracts/Event.sol
language/evm/hardhat-examples/contracts/FortyTwo.sol
language/evm/hardhat-examples/contracts/Greeter.sol
language/evm/hardhat-examples/contracts/Native.abi.json
language/evm/hardhat-examples/contracts/Native.move
language/evm/hardhat-examples/contracts/Native.sol
language/evm/hardhat-examples/contracts/Revert.abi.json
language/evm/hardhat-examples/contracts/Revert.move
language/evm/hardhat-examples/contracts/Revert.sol
language/evm/hardhat-examples/package-lock.json
language/evm/hardhat-examples/package.json
language/evm/hardhat-examples/test/Event.test.js
language/evm/hardhat-examples/test/Native.test.js
language/evm/hardhat-examples/test/Revert.test.js
language/evm/stdlib/sources/Evm.move

Added the following contracts and their tests:
- Event: to test the event emission
- Revert: to test reverting with/without a custom message
- Native: to test the native functions such as `self()` and `sender()`
TODO:
- move-to-yul does not support events with string arguments. the Move contracts fail on the tests of Event and Revert. https://github.com/diem/move/issues/170
- Move-on-EVM should be able to revert (or abort) with a custom error message. https://github.com/diem/move/issues/171
To add more hardhat examples for testing Move-on-Evm
yes
hardhat test

[evm] Added more hardhat examples

---

language/evm/hardhat-examples/contracts/Token.abi.json
language/evm/hardhat-examples/contracts/Token.move
language/evm/hardhat-examples/test/Token.test.js
language/evm/move-to-yul/src/attributes.rs
language/evm/move-to-yul/src/dispatcher_generator.rs
language/evm/move-to-yul/src/generator.rs
language/evm/move-to-yul/tests/ConstructorTest.exp
language/evm/move-to-yul/tests/ConstructorTest.move

This PR enables signature and arguments for the constructor of move contracts.
Yes
The Token example in hardhat-examples

[move-to-yul] Add support for constructor with arguments

---

language/evm/hardhat-examples/compile_all_and_test.sh
language/evm/hardhat-examples/compile_sol_and_test.sh
language/evm/hardhat-examples/contracts/Event.abi.json
language/evm/hardhat-examples/contracts/Event.move
language/evm/hardhat-examples/contracts/Event.sol
language/evm/hardhat-examples/contracts/FortyTwo.sol
language/evm/hardhat-examples/contracts/Greeter.sol
language/evm/hardhat-examples/contracts/Native.sol
language/evm/hardhat-examples/contracts/Revert.sol
language/evm/hardhat-examples/test/Event.test.js
language/evm/hardhat-examples/test/FortyTwo.test.js
language/evm/hardhat-examples/test/Greeter.test.js
language/evm/hardhat-examples/test/Native.test.js
language/evm/hardhat-examples/test/Revert.test.js
language/evm/hardhat-examples/test/Token.test.js

- Added the suffix `_Sol` to the names of the Solidity contracts so that they don't conflict with the Move contract names
- Duplicated the hardhat tests, so one is for the Move contracts, and another is for the Solidity contracts, and they don't overlap
- Merged the automated test scripts. `compile_all_and_test.sh` will compile both Move and Solidity contracts and test them.
- Fixed the test failures in the Event contract. Closes #170 
TODO:
- move-to-yul does not support string literals.
To update the hardhat examples for Move
yes
./compile_all_and_test.sh

[evm] Separated the Move contract tests from the Solidity contract tests

---

language/move-vm/test-utils/src/storage.rs

To unblock downstream tests.
In Aptos repo we are trying to enforce the table extension to be installed everywhere, and this not supporting tables breaks compilation.
y
Downsteam tests pass

stub `impl TableResolver` for DeltaStorage

---

language/extensions/async/move-async-vm/src/async_vm.rs
language/move-vm/runtime/src/loader.rs
language/move-vm/runtime/src/move_vm.rs
language/move-vm/runtime/src/runtime.rs
language/move-vm/runtime/src/session.rs
language/move-vm/types/src/loaded_data/runtime_types.rs

- Exposing more access to the cache gives adapters more flexibility
- Allows adapters to implement checks over cached data (without having to make their own cache)
- eyes. endpoints are already tested, just now expoed

[move-vm] Expose more function and type APIs in the session

---

language/evm/hardhat-examples/contracts/ERC721ReceiverMock.sol
language/evm/hardhat-examples/contracts/ExternalCall/Move.toml
language/evm/hardhat-examples/contracts/ExternalCall/sources/ExternalCall.move
language/evm/hardhat-examples/contracts/Native.sol
language/evm/hardhat-examples/contracts/Native/sources/Native.move
language/evm/hardhat-examples/package-lock.json
language/evm/hardhat-examples/test/ExternalCall.test.js
language/evm/hardhat-examples/test/Native.test.js
language/evm/move-to-yul/src/native_functions.rs
language/evm/stdlib/sources/Evm.move

This commit:
- implements the isContract function by implementing the Evm::extcodesize native function.
- adds minimal test cases to reproduce the following two bugs in handling external calls.
- To implement isContract, and add test cases for external calls
Yes

[evm] Implements isContract, and more test cases for external calls(#33)_14

---

language/tools/move-resource-viewer/src/lib.rs
language/tools/move-resource-viewer/src/resolver.rs

As script function can support more flexible parameters, we plan to enable passing signer reference instead of signer in script and script function to reduce redundant code. Ex: developer has to write script function taking signer and a internal version of script function to take &signer so that they can test with internal version of function without worrying about the signer value being "moved". This leads to lot of code duplication and force developer to understand unnecessary language details.
The move viewer also has the same assumption that should be relaxed. When API reads the onchain TXN data and rendered the data for better visualization. It needs to convert the txn args back from BCS to it original string representation. When it does this converion, It has the assumption that txn …

exclude &signer in view_function_arguments (#77)_39

---

language/move-compiler/src/expansion/aliases.rs
language/move-compiler/src/expansion/translate.rs
language/move-compiler/tests/move_check/naming/friend_decl_self.exp

- In short, we want to preserve locations of identifiers that are aliases to modules or module-level definitions. It fixes the problem more generally (e.g., also for Pack and other AST nodes).
CI/CD Tests were covered

Added support for preserving locations of aliased identifiers (#103)_48

---

language/extensions/move-table-extension/sources/Table.move
language/extensions/move-table-extension/src/lib.rs
language/extensions/move-table-extension/tests/TableTests.move

This PR adds trait bounds (copy + drop) to the key
Cargo test

Add Table key bound with copy + drop (#109)_49  AB#8969

---

language/testing-infra/transactional-test-runner/src/framework.rs

- fix test failure on compare lines ending with "\r\n" and "\n"
- Cargo test

fix test failure on compare lines ending with "\r\n" and "\n" (#132)_57

---

language/tools/move-cli/src/sandbox/commands/test.rs
language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/Move.toml
language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/args.evm.exp
language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/args.evm.txt
language/tools/move-cli/tests/build_tests/rebuild_after_adding_new_source/sources/Foo.move
language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/Move.toml
language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/args.evm.exp
language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/args.evm.txt
language/tools/move-cli/tests/build_tests/rebuild_after_deleting_output_artifact/sources/Foo.move
language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/Move.toml
language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/args.evm.exp
language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/args.evm.txt
language/tools/move-cli/tests/build_tests/rebuild_after_touching_manifest/sources/Foo.move
language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/Move.toml
language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/args.evm.exp
language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/args.evm.txt
language/tools/move-cli/tests/build_tests/rebuild_after_touching_source/sources/Foo.move
language/tools/move-cli/tests/build_tests/rebuild_no_modification/Move.toml
language/tools/move-cli/tests/build_tests/rebuild_no_modification/args.evm.exp
language/tools/move-cli/tests/build_tests/rebuild_no_modification/args.evm.txt
language/tools/move-cli/tests/build_tests/rebuild_no_modification/sources/Foo.move
language/tools/move-package/src/compilation/build_plan.rs
language/tools/move-package/src/lib.rs

This implements some basic caching mechanism for move package build --arch ethereum. Recompilation will only be triggered when any of the following conditions is met:
1. Any of the sources has been modified, or more precisely, has a modification time later than those of the outputs.
2. Any expected output file is missing.
cargo test

[move package] rebuild only if sources have been modified or outputs are missing or outdated #97_63

---

language/tools/move-package/src/compilation/build_plan.rs

With this change, `move package build --arch Ethereum` now removes the` build/evm `directory before generating the new artifacts.
Yes

[evm][move package] remove build dir before starting a new build #105_66

---

language/tools/move-cli/src/package/cli.rs
language/tools/move-package/src/lib.rs

Previously, the --arch ethereum option is only present when feature evm-backend is enabled, which ended up causing some confusion. This PR makes the option always available, but return an error if evm-backend isn't enabled when invoked.
CI/CD Tests are covered

[evm][move package] make --arch ethereum present in all builds, but return an error if feature evm-backend isn't enabled #106_67 AB#8969

---

README.md
docker/move-cli/Dockerfile

Added Dockerfile for Move command-line interface for getting started
easier. This Dockerfile is based on the CI image found in docker/.
- Also added building instructions to README.
- Providing an easier way to get started with Move.
- This Dockerfile can later be used with automated packaging solutions, such as Docker Hub.
Yes 
CI/CD Tests are covered

[docker] Added Dockerfile for the Move CLI #130_75

---

language/move-analyzer/src/bin/move-analyzer.rs
language/move-analyzer/src/context.rs
language/move-analyzer/src/symbols.rs
language/move-analyzer/src/vfs.rs

This is a refinement for the recently added (https://github.com/diem/move/pull/365) symbolication support in the language server. The purpose of the original PR (https://github.com/diem/move/pull/365) was to introduce (and test) the symbolication algorithm itself.
The goal of this PR is to move the needle in terms of user experience - in the original PR, symbolication was triggered only once at the language server start. In this PR we trigger symbolication asynchronously (in a separate thread) each time a file is saved so that the most recent information about symbols is available to the IDE.
One reason to use only a single symbolicator thread is to throttle the number of times symbolication (which is relatively expensive) is triggered. At this point it's not a big issue as it's triggered …

[language server] Async symbolication on file saves #163_89

---

Cargo.lock
language/move-analyzer/Cargo.toml
language/move-analyzer/editors/code/package-lock.json
language/move-analyzer/src/bin/move-analyzer.rs
language/move-analyzer/src/completion.rs
language/move-analyzer/src/diagnostics.rs
language/move-analyzer/src/lib.rs
language/move-analyzer/src/symbols.rs
language/move-analyzer/src/utils.rs
language/move-analyzer/src/vfs.rs

This another refinement of recently added support for more advanced language server features (https://github.com/diem/move/pull/365). This PR adds support for passing compiler diagnostics from the language server to the IDE (so that it is more clear why advanced features may not work or work in a limited fashion when the compilation fails).
This PR also fixes an ongoing problem with auto-completion where the loop where lexing problems could lead to a loop collecting identifiers from a file to run forever.
Finally, supporting lexer diagnostics, particularly in the limited way they were supported, does not make much sense now that we have compiler diagnostics so the lexer ones have been removed.
CI/CD tests are performed

[language server] Added support for displaying compiler diagnostics #165_90

---

language/move-analyzer/src/bin/move-analyzer.rs
language/move-analyzer/src/symbols.rs

One more refinement of recently added support for more advanced language server features. This PR is about passing "fatal" compilation errors (i.e., those that do not result in generating diagnostics for the source code) back to IDE so that it's more explicit why more advanced features (i.e., those relying on successful compilation) may not work as expected.
Enabled advanced functionality in the server to simplify deployment, but it's not meant for wider consumption yet as it requires the extension to be re-published for the new functionality to work.
CI/CD tests were covered.

[language server] Added support for passing compilation errors back to the IDE #167_93

---

language/move-analyzer/editors/code/package-lock.json
language/move-analyzer/editors/code/package.json
language/move-analyzer/editors/code/tests/ext.test.ts
language/move-analyzer/editors/code/tests/index.ts
language/move-analyzer/editors/code/tests/runTests.ts

This PR resurrects the extension testing framework "as is" with respect to its version when it was removed in https://github.com/diem/move/pull/404 (as there was nothing to test at that time). 
The changes in package-lock.json, while seemingly extensive, are due to a change in the file format brought in by the new npm version (lockfileVersion changed from 1 to 2) rather than massive changes in dependencies.
The changes in package.json are minimal (2 lines of code to enable tests in the scripts) but the file is being reformatted as part of the build/test process (e.g., npm run test), possibly due to us now running newer version of npm/node so we should just bite the bullet once and be done with it.
CI/CD Tests were performed

[Move analyzer] Resurrected testing framework #228_123

---

Cargo.lock
language/tools/move-unit-test/Cargo.toml
language/tools/move-unit-test/src/extensions.rs
language/tools/move-unit-test/src/lib.rs

Until now, extensions leveraged by the Move UT infra had to live in the Move repo.
This PR adds a hook which can be used as in move_unit_tests::extensions::set_extension_hook(fun),
where fun is populating a NativeContextExtensions for the according custom environment. 
Yes

[unit-test] Allow extensions used for unit testing to live outside of Move repo #245_135

---

language/move-analyzer/src/symbols.rs

A missing manifest message should be more meaningful to allow developers to act on it more easily.
Yes

[Move analyzer] Added a more meaningful missing manifest message #233_133

---

language/move-prover/boogie-backend/src/lib.rs
language/move-prover/boogie-backend/src/options.rs

This PR updates boogie backend options so that we use bytes instead of file path in CustomNativeOptions.

[move prover] use bytes instead of file path in CustomNativeOptions #253_140

---

language/tools/move-cli/src/sandbox/cli.rs
language/tools/move-cli/src/sandbox/commands/publish.rs
language/tools/move-cli/tests/sandbox_tests/cyclic_multi_module_publish/args.exp
language/tools/move-cli/tests/sandbox_tests/cyclic_multi_module_publish/args.txt
language/tools/move-cli/tests/sandbox_tests/multi_module_publish/args.exp
language/tools/move-cli/tests/sandbox_tests/multi_module_publish/args.txt

This PR contains two changes to the move-cli sandbox publish interface:
-  [move-cli] add --with-deps option to the publish command
The default scenario is to publish the modules within the package only,
excluding the modules compiled from its dependency packages. This
--with-deps flag, when set, will allow modules in the deps packages
to be published as well, together with the package root modules.
-  [move-cli] allow multi-module publishing in Move CLI with --bundle
The current default mode of publishing in Move CLI is sequential,
i.e., one-module-at-a-time. This means that modules that are cyclic
dependent cannot be published all at once (e.g., the DPN in the
documentation/examples directory).
To show this issue, run:
```
cd language/documentation/examples/diem-framework/move-packages/D …
```

[move-cli] sandbox publishing with multiple modules and optionally, all modules in a package #261_153

---

language/move-vm/runtime/src/session.rs

Until now this have been hidden inside the session and only accessible from within native functions. This makes them also accessible outside so we can work with them on session level (e.g. for lazy code loading).
Yes

[vm] Allow access to native extensions via the session. #293_162

---

language/extensions/move-table-extension/sources/Table.move
language/extensions/move-table-extension/src/lib.rs
language/move-vm/test-utils/src/storage.rs
language/tools/move-unit-test/src/extensions.rs

Getting this information requires deep understanding of changesets to otherwise get the typeinfo for the key and value. And doing so expensive. This is relatively cheap and can be used by the node to support lookup and decoding of types in storage.
Yes

[table] add information about the table types when adding new tables #272_165

---

language/move-prover/boogie-backend/src/bytecode_translator.rs
language/move-prover/tests/sources/functional/aborts_if_with_code.exp
language/move-prover/tests/sources/functional/global_invariants.exp
language/move-prover/tests/sources/functional/invariants.exp
language/move-prover/tests/sources/functional/is_txn_signer.exp
language/move-prover/tests/sources/functional/loops.exp
language/move-prover/tests/sources/functional/loops_with_memory_ops.exp
language/move-prover/tests/sources/functional/macro_verification.exp
language/move-prover/tests/sources/functional/trace.exp

The Move prover does not print the correct line number in some error traces. Consider the example below.
```
public fun test_loop(x: u64) {
if (x != 0) {
x = 1;
}
else {
x = 2;
};
spec {
assert x == 1;
};
}
```
The following error trace is given.
```
error: unknown assertion failed
┌─ ./sources/loop.move:9:9
│
9 │         assert x == 1;
│         ^^^^^^^^^^^^^^
│
=     at ./sources/loop.move:1: test_loop
=         x = 0
=     at ./sources/loop.move:2: test_loop
=         x = 2
=     at ./sources/loop.move:8: test_loop
=     at ./sources/loop.move:9: test_loop
```
However, the assignment `x = 2` occurs at Line 6 rather than Line 2. This pull request will insert at  `./sources/loop.move:6: test_loop` above `x = 2`.
cargo test --release

[move-prover] Add missing location line in error trace #297_163
