language/evm/move-to-yul/src/generator.rs, language/evm/move-to-yul/src/yul_functions.rs, language/evm/move-to-yul/tests/Structs.exp, language/evm/move-to-yul/tests/Structs.move
This adds Load/StoreU128 which was unimplemented for now. It also refactors the handling of type instantiations a bit.
EVM
Yes
Baseline
=> [move-to-yul] Add 128 bit support and some cleanup

language/tools/move-bytecode-utils/src/layout.rs
No need to panic here, just makes life harder for a caller that made a mistake.
=> [cleanup] return Result instead of panic-ing in TypeLayoutBuilder

scripts/dev_setup.sh
I needed to run devsetup from scratch on my WSL installation and came accross this issue. However, not sure whether I like the solution (sudo on a downloaded script?)
Yes
=> [devsetup] Adding misssing sudo for nodejs install

Cargo.lock, language/evm/move-to-yul/Cargo.toml
This is a dummy PR to test bors which seems to be down. It removes some unneeded deps from move-to-yul.
Yes
=> [move-repo] PR to test bors.

language/documentation/book/README.md
This PR adds a README to the Move book on how to build it and update the Move book website.
=> [book] Add README on building and updating the Move book

language/move-core/types/src/language_storage.rs, language/move-core/types/src/value.rs
Fix the issues described here https://github.com/diem/move/issues/126
Yes
cargo x lint && cargo xfmt && cargo xclippy --all-targets passed
cargo test -p move-core-types passed
=> Fix serde serialization leading to compile error

README.md
Adding an awesome list "awesome-move", the directory of code and
content from the Move programming language community.
The awesome-move list can be used as one of the building blocks to build the Move community.
Yes.
No test plan needed: pure documentation.
No related PRs.
=> [README] Adding awesome-move to the Community section

language/evm/hardhat-examples/contracts/Event.move, language/evm/hardhat-examples/contracts/Event.sol, language/evm/hardhat-examples/test/Revert.test.js, language/evm/hardhat-examples/test/Revert.truffle.test.js
- fixed the issue with emitting events with indexed arguments
- added a Truffle-style test for Revert
resolves #185 
to fix the failed test
yes
`./compile_all_and_test.sh`
=> [evm] Fixed the event issue

language/move-analyzer/editors/code/README.md
Part of the description and links were out-of-date due to Move repository's modified location.
Yes
=> [docs] Updated Move analyzer readme file to reflect new Move repo location

language/evm/hardhat-examples/contracts/ERC20DecimalsMock.abi.json, language/evm/hardhat-examples/contracts/ERC20DecimalsMock.move, language/evm/hardhat-examples/contracts/ERC20Mock.abi.json, language/evm/hardhat-examples/contracts/ERC20Mock.move, language/evm/hardhat-examples/scripts/deploy_erc20mock.js, language/evm/hardhat-examples/test/ERC20.behavior.js, language/evm/hardhat-examples/test/ERC20.test.js, language/evm/stdlib/sources/Evm.move, language/evm/stdlib/sources/U256.move
- Created ERC20 Move contracts for Hardhat such ERC20Mock, ERC20DecimalsMock
- Added the openzeppelin tests for ERC20
- Checked that all the tests passed
To add ERC20 Move contracts
yes
./compile_all_and_run_tests.sh
=> [evm] Added ERC20 Move contracts to the hardhat project

Cargo.lock, crates/workspace-hack/Cargo.toml, devtools/x/Cargo.toml, language/move-analyzer/Cargo.toml, language/move-compiler/Cargo.toml, language/move-ir-compiler/Cargo.toml, language/move-prover/Cargo.toml, language/move-prover/interpreter/Cargo.toml, language/move-prover/lab/Cargo.toml, language/move-prover/mutation/Cargo.toml, language/move-prover/tools/spec-flatten/Cargo.toml, language/testing-infra/test-generation/Cargo.toml, language/testing-infra/transactional-test-runner/Cargo.toml, language/tools/mirai-dataflow-analysis/Cargo.toml, language/tools/move-bytecode-viewer/Cargo.toml, language/tools/move-cli/Cargo.toml, language/tools/move-coverage/Cargo.toml, language/tools/move-disassembler/Cargo.toml, language/tools/move-explain/Cargo.toml, language/tools/move-package/Cargo.toml, language/tools/move-unit-test/Cargo.toml
- bump clap from 3 to 3.1.8
- pulling in some changes to ArgEnum
- ran em
=> Bump clap version

language/move-vm/runtime/src/interpreter.rs, language/move-vm/runtime/src/loader.rs, language/move-vm/runtime/src/runtime.rs, language/move-vm/runtime/src/session.rs, language/move-vm/transactional-tests/tests/builtins/vector_ops_using_generics.exp, language/move-vm/transactional-tests/tests/builtins/vector_ops_using_generics.mvir
- allow for easy adapter rules, as was similarly intended with the load_function API
- Fix some vector operations
Yes
=> Add load_script to session API (#35)_15

language/evm/hardhat-examples/contracts/ExternalCall/sources/ExternalCall.move, language/evm/hardhat-examples/test/ExternalCall.test.js, language/evm/hardhat-move/package-lock.json, language/evm/move-to-yul/src/external_functions.rs, language/evm/move-to-yul/tests/test-dispatcher/ExternalCall.exp
Fix issue on allocating memory for external call
Yes
CI/CD tests are covered
=> Fix issue on allocating memory for external call (#36)_16

language/testing-infra/transactional-test-runner/src/framework.rs, language/testing-infra/transactional-test-runner/src/tasks.rs, language/testing-infra/transactional-test-runner/src/vm_test_harness.rs, language/testing-infra/transactional-test-runner/tests/vm_test_harness/leading_comment.exp, language/testing-infra/transactional-test-runner/tests/vm_test_harness/leading_comment.move
Support leading comments at the beginning of the test file
Helpful for copyright information and test descriptions
Add optional default value for named addresses on miss
Yes
=> Leading comment (#92)_47

language/move-prover/tests/sources/functional/nonlinear_arithm.exp, language/move-prover/tests/sources/functional/nonlinear_arithm.move
Disable prover test which fails on smaller machines
Yes
=> Disable prover test which fails on smaller machines. (#114)_51

language/move-compiler/src/parser/lexer.rs
* [move-compiler] fix invalid character cr when match tab cr lf
* feat: add trim_whitespace func and this func's unit-test
* feat: update trim_whitespace annotate
* feat: add test case for single \r
* feat: recover trim_whitespace_and_comments name
* feat: simplify the trim_start_whitespace function
Yes
CI/CD test cases will cover above changes
=> fix invalid character cr when match tab cr lf (#116)_53 AB#8967

Cargo.lock, language/tools/move-package/Cargo.toml, language/tools/move-package/src/source_package/manifest_parser.rs
fix `HOME environment variable not found` on Windows platform
CI/CD Tests are covered
=> fix `HOME environment variable not found` on Windows platform (#133)_58

language/move-prover/tests/sources/functional/verify_sort.move, language/move-prover/tests/sources/functional/verify_vector.move
Added a Prover test for verifying a sorting function 
Yes
cargo test
=> Added a Prover test for verifying a sorting function (#155)_60

language/move-stdlib/docs/Option.md, language/move-stdlib/sources/Option.move, language/move-stdlib/tests/OptionTests.move
add function to convert option to vector
Yes
=> [stdlib] add function to convert option to vector (#180)__87

language/move-analyzer/src/symbols.rs
This PR implements a few fixes for displaying compiler diagnostics in the IDE:
- The changes for displaying warnings implemented and have been accidentally reverted and now they are brought back in
- we now still compute new diagnostics even if the to-bytecode-compilation fails but we still have the typed AST available.
- we now explicitly reset diagnostics for files that no longer have any errors/warnings.
Yes
=> [Move] Fixed displaying compiler diagnostics in the IDE (#225)_124

language/move-analyzer/editors/code/README.md, language/move-analyzer/src/bin/move-analyzer.rs
Now that we have updated the VSCode plugin and the language server with new features, we bump up language server's version number and a feature set in the README file to reflect the current state of affairs.
Yes
=> [Move analyzer] Updated version number and added new features to the docs #230_128

language/tools/move-cli/src/package/cli.rs
If we want to re-use any of the code used in core Move for creating package directory structure, we need to do a bit of refactoring.
On the one hand, perhaps it's an overkill as this code does not do much, but I still don't like the idea of doing copypaste from core Move to other Move flavors to support this.
On the other hand, perhaps this could be more generalized (e.g., have vectors of dependency/address info). I'd think we can get there when/if we have to, but it's obviously subjective.
Yes
=> [CLI] Parameterized new package creation for better reuse #235_129

language/extensions/move-table-extension/Move.toml, language/extensions/move-table-extension/README.md, language/extensions/move-table-extension/sources/Table.move, language/extensions/move-table-extension/sources/Table.spec.move, language/extensions/move-table-extension/src/lib.rs, language/extensions/move-table-extension/tests/table_tests.move, language/move-model/src/well_known.rs, language/move-prover/boogie-backend/src/prelude/native.bpl, language/move-prover/tests/sources/functional/verify_table.move, language/move-prover/tests/testsuite.rs
To make the move-table-extension package lowercase
cargo test
=> [Prover] Make the move-table-extension package lowercase #282_156

language/tools/move-cli/src/base/coverage.rs, language/tools/move-cli/src/base/disassemble.rs, language/tools/move-cli/src/base/errmap.rs, language/tools/move-cli/src/base/new.rs, language/tools/move-cli/src/base/prove.rs, language/tools/move-cli/src/base/test.rs, language/tools/move-cli/src/lib.rs
[move-cli] Make command fields pub
=> [move-cli] Make command fields pub #247_167
